from typing import Any
from .catalog_service import get_budgeted_catalog
from .gemini_utils import generate_recommendation


def _sum_prices(items):
    return sum(float(i.get("price", 0)) for i in items)


def fallback_home(payload: dict[str, Any], catalog: list[dict[str, Any]]):
    budget = float(payload["budget"])
    selected = []
    total = 0
    for item in catalog:
        if total + item["price"] <= budget * 0.92:
            selected.append({**item, "reason": f"Fits the {payload['style']} style and leaves room in the budget."})
            total += item["price"]
        if len(selected) >= 6:
            break
    allocation = {"Furniture": round(budget * .40, 2), "Lighting": round(budget * .20, 2), "Decor": round(budget * .25, 2), "Storage": round(budget * .15, 2)}
    return {"summary": f"A {payload['style']} home setup for {', '.join(payload['rooms'])}, keeping the plan under ₹{budget:,.0f}.", "allocation": allocation, "recommendations": selected, "tips": ["Measure the room before buying large furniture.", "Reserve part of the budget for delivery and installation."]}


def fallback_party(payload: dict[str, Any], catalog: list[dict[str, Any]]):
    budget = float(payload["budget"])
    guests = int(payload["guest_count"])
    selected = []
    total = 0
    for item in catalog:
        estimated = item["price"] * guests if item["category"] == "Catering" else item["price"]
        if total + estimated <= budget * .92:
            copy = {**item, "reason": "Selected as a practical option for the event budget."}
            copy["price"] = round(estimated, 2)
            selected.append(copy)
            total += estimated
        if len(selected) >= 5:
            break
    allocation = {"Catering": round(budget * .50, 2), "Decoration": round(budget * .20, 2), "Venue": round(budget * .20, 2), "Entertainment": round(budget * .10, 2)}
    return {"summary": f"A {payload['event_type']} plan for {guests} guests with a ₹{budget:,.0f} budget.", "allocation": allocation, "recommendations": selected, "tips": ["Confirm per-person catering rates before booking.", "Keep a small contingency amount for last-minute needs."]}


def fallback_jewelry(payload: dict[str, Any], catalog: list[dict[str, Any]]):
    budget = float(payload["budget"])
    selected = []
    total = 0
    for item in catalog:
        if total + item["price"] <= budget * .92:
            selected.append({**item, "reason": f"Works as a {payload['style']} option for a {payload['occasion']} occasion."})
            total += item["price"]
        if len(selected) >= 5:
            break
    allocation = {"Necklace": round(budget * .45, 2), "Earrings": round(budget * .30, 2), "Bracelet": round(budget * .15, 2), "Reserve": round(budget * .10, 2)}
    return {"summary": f"Jewelry suggestions for a {payload['occasion']} occasion with a {payload['style']} preference, within ₹{budget:,.0f}.", "allocation": allocation, "recommendations": selected, "tips": ["Check the seller's current specifications before ordering.", "Match the metal tone with the outfit accessories for a coordinated look."]}


def make_recommendation(planner_type: str, payload: dict[str, Any], image_path: str | None = None):
    catalog = get_budgeted_catalog(planner_type, float(payload["budget"]))
    ai_data, ai_used = generate_recommendation(planner_type, payload, catalog, image_path)
    if ai_data:
        # Sanitize AI output against the candidate catalog and budget.
        allowed = {(x["name"], x["platform"]): x for x in catalog}
        clean = []
        remaining = float(payload["budget"])
        for item in ai_data.get("recommendations", []):
            key = (item.get("name"), item.get("platform"))
            source = allowed.get(key)
            if not source or source["price"] > remaining:
                continue
            clean.append({**source, "reason": str(item.get("reason", "Budget-aware recommendation."))})
            remaining -= source["price"]
        ai_data["recommendations"] = clean
        ai_data["allocation"] = {str(k): float(v) for k, v in (ai_data.get("allocation") or {}).items()}
        ai_data["tips"] = [str(x) for x in (ai_data.get("tips") or [])][:6]
        ai_data["summary"] = str(ai_data.get("summary", "Budget-aware recommendations generated by Gemini."))
        return ai_data, True
    fallback = {"home": fallback_home, "party": fallback_party, "jewelry": fallback_jewelry}[planner_type](payload, catalog)
    return fallback, False
